version: 2
jobs:
  build:
    branches:
      only:
        - master
        - dev
        - /back-.*/
        - /feature-.*/
    docker:
      - image: circleci/node:10.15
    working_directory: ~/premedium
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test